### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by arunpt** [oxdev03/pm2.web#25]
When i try to deploy dashboard in vercel I'm getting erros in npm that some packages are not exist
![image](https://github.com/oxdev03/pm2.web/assets/46273006/84cc36a4-eb6b-47f9-9883-d4142e888aee)

**Comment by oxdev03** [comment]
Hi,
could you check, if the root dir is configured correctly?

![Screenshot_20240615_155034_Brave](https://github.com/oxdev03/pm2.web/assets/140103378/a40f6216-be2a-400f-a9d7-f923b103f653)

**Comment by arunpt** [comment]
I tried it, and it didn't work. The repository URL with the path to the dashboard is already set up in vercel, so mentioning it in the configuration isn't necessary since that folder doesn't exist.
![image](https://github.com/oxdev03/pm2.web/assets/46273006/db57ff98-6c1c-41ce-b7d1-2886c5f231e6)

**Comment by oxdev03** [comment]
thank you, the deployment url is incorrect. Since apparently vercel only clones that directory. I am currently working on a fix, till then you can remove the `apps/dashboard` from the url and set the Root Directory and `Build & Development Settings > Framework Preset` (Redeploy required)
