### ISSUE TITLE
backend cant handle jar process

### ISSUE THREAD

**Issue by theblackangelx** [oxdev03/pm2.web#40]
I am currently running a jar file using pm2 it works but the web interface doenst like it

6:51:15 PM [pm2.web-daemon] backend:start: Error: Process validation failed: type: `none` is not a valid enum value for path `type`.
backend:start:     at ValidationError.inspect (/root/sparkbot/Dashboard/node_modules/mongoose/lib/error/validation.js:50:26)
backend:start:     at formatValue (node:internal/util/inspect:805:19)
backend:start:     at inspect (node:internal/util/inspect:364:10)
backend:start:     at formatWithOptionsInternal (node:internal/util/inspect:2279:40)
backend:start:     at formatWithOptions (node:internal/util/inspect:2141:10)
backend:start:     at console.value (node:internal/console/constructor:343:14)
backend:start:     at console.log (node:internal/console/constructor:380:61)
backend:start:     at /root/sparkbot/Dashboard/apps/backend/dist/handlers/updateData.js:74:25
backend:start:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
backend:start:     at async updateData (/root/sparkbot/Dashboard/apps/backend/dist/handlers/updateData.js:73:13) {
backend:start:   errors: {
backend:start:     type: ValidatorError: `none` is not a valid enum value for path `type`.
backend:start:         at validate (/root/sparkbot/Dashboard/node_modules/mongoose/lib/schemaType.js:1385:13)
backend:start:         at SchemaType.doValidate (/root/sparkbot/Dashboard/node_modules/mongoose/lib/schemaType.js:1369:7)
backend:start:         at /root/sparkbot/Dashboard/node_modules/mongoose/lib/document.js:3071:18
backend:start:         at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
backend:start:       properties: [Object],
backend:start:       kind: 'enum',
backend:start:       path: 'type',
backend:start:       value: 'none',
backend:start:       reason: undefined,
backend:start:       [Symbol(mongoose#validatorError)]: true
backend:start:     }
backend:start:   },
backend:start:   _message: 'Process validation failed'
backend:start: }

**Comment by oxdev03** [comment]
Hi,
thx for the issue. I will have a look into it.
